name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1

  http: ^0.13.6
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.9
  smooth_page_indicator: ^1.1.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/images/on_boarding_images/
    - assets/icons/
    - assets/logos/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800